CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260325003723_InitialPostgres') THEN
    CREATE TABLE "Produtos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(150) NOT NULL,
        "Descricao" character varying(500),
        "Preco" numeric(18,2) NOT NULL,
        "QuantidadeEmEstoque" integer NOT NULL,
        "DataCadastro" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Produtos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260325003723_InitialPostgres') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(150) NOT NULL,
        "Email" character varying(200) NOT NULL,
        "SenhaHash" text NOT NULL,
        "DataCadastro" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260325003723_InitialPostgres') THEN
    CREATE TABLE "MovimentacoesEstoque" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProdutoId" integer NOT NULL,
        "Tipo" character varying(20) NOT NULL,
        "Quantidade" integer NOT NULL,
        "Data" timestamp with time zone NOT NULL,
        "Observacao" character varying(500),
        CONSTRAINT "PK_MovimentacoesEstoque" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovimentacoesEstoque_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produtos" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260325003723_InitialPostgres') THEN
    CREATE INDEX "IX_MovimentacoesEstoque_ProdutoId" ON "MovimentacoesEstoque" ("ProdutoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260325003723_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_Email" ON "Usuarios" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260325003723_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260325003723_InitialPostgres', '8.0.13');
    END IF;
END $EF$;
COMMIT;

